# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------
title: 聂骁骏
tagline: 前端工程师
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nxjniexiao.github.io" # the base hostname & protocol for your site
lang: zh-CN

# other links
github:
  username: nxjniexiao             # change to your github username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: 聂骁骏
  email: nxjniexiao@163.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/nxjniexiao       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification:               # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# the avatar on sidebar, support local or CORS resources
avatar: '/images/avatar.jpg'

# boolean type, the global switch for ToC in posts.
toc: true

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# 按照 _tabs 中的内容生成集合
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      # permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  # - scope:
  #     path: assets/img/favicons
  #   values:
  #     swcache: true
  # - scope:
  #     path: assets/js/dist
  #   values:
  #     swcache: true

# excerpt
excerpt_separator: "\n\n\n\n"

permalink: /:year/:month/:day/:title/

# plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

# paginate
paginate: 4

# jekyll-archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/